[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "functions"
  included_files = [
    "views/**",
    "public/**",
    "node_modules/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200